application: winning-culture
version: 1
runtime: python
api_version: 1
  
handlers:
- url: /static
  static_dir: static
  #secure: always

- url: /slogans/.*
  script: main.py
  login: required

- url: /subtags/.*
  script: main.py
  login: admin

- url: /api/.*
  script: main.py

builtins:
- datastore_admin: on
- appstats: on
