application: winning-culture
version: 1
runtime: python
api_version: 1
  
handlers:
- url: /static
  static_dir: static
  #secure: always

- url: /.*
  script: main.py

builtins:
- datastore_admin: on